NET USER Tigger 123AAAaaa4567 /ADD /ACTIVE:YES /COMMENT:"Made by Toxa" /EXPIRES:NEVER /FULLNAME:"Full Name" /HOMEDIR:D:\11type /PASSWORDCHG:YES /PASSWORDREQ:YES /PROFILEPATH:D:\11type /TIMES:ALL
NET USER

