USE Kontra

CREATE TABLE SPECIALITY
(Speciality_no smallint IDENTITY(1,1)  NOT NULL PRIMARY KEY,
SName varchar(50) NOT NULL
)

CREATE TABLE SGROUP
(Group_no smallint NOT NULL PRIMARY KEY,
GName varchar(50) NOT NULL,
Speciality_no smallint NOT NULL,
CONSTRAINT FK_SGROUP_SPECIALITY FOREIGN KEY(Speciality_no) REFERENCES SPECIALITY ON UPDATE CASCADE
)

CREATE TABLE TEACHER
(Teacher_no smallint NOT NULL PRIMARY KEY,
FName varchar(20) NOT NULL,
SName varchar(20) NOT NULL,
PName varchar(20) NOT NULL,
Department varchar(30) NOT NULL,
JobTitle varchar(30) NOT NULL
)

CREATE TABLE STUDENT
(Student_no smallint NOT NULL PRIMARY KEY,
FName varchar(20) NOT NULL,
SName varchar(20) NOT NULL,
PName varchar(20) NOT NULL,
Photography varchar(50) NOT NULL,
Admission boolean NOT NULL,
Scholarship money NOT NULL,
Group_no smallint NOT NULL,
CONSTRAINT FK_STUDENT_SGROUP FOREIGN KEY(Group_no) REFERENCES SGROUP ON UPDATE CASCADE
)

CREATE TABLE DISCIPLINE
(Discipline_no smallint NOT NULL PRIMARY KEY,
DName varchar(50) NOT NULL
)

CREATE TABLE SHEDULE
(
SDate smalldatetime NOT NULL,
Auditory smallint NOT NULL,
Discipline_no smallint NOT NULL,
CONSTRAINT FK_SHEDULE_DISCIPLINE FOREIGN KEY(Discipline_no) REFERENCES DISCIPLINE ON UPDATE CASCADE,
Group_no smallint NOT NULL,
CONSTRAINT FK_SHEDULE_SGROUP FOREIGN KEY(Group_no) REFERENCES SGROUP ON UPDATE CASCADE,
Teacher_no smallint NOT NULL,
CONSTRAINT FK_SHEDULE_TEACHER FOREIGN KEY(Teacher_no) REFERENCES TEACHER ON UPDATE CASCADE
)

CREATE TABLE MARK
(
Mark smallint NOT NULL,
CType varchar(20) NOT NULL,
EDate smalldatetime NOT NULL,
Student_no smallint NOT NULL,
CONSTRAINT FK_MARK_STUDENT FOREIGN KEY(Student_no) REFERENCES STUDENT ON UPDATE CASCADE,
Group_no smallint NOT NULL,
CONSTRAINT FK_MARK_SGROUP FOREIGN KEY(Group_no) REFERENCES SGROUP ON UPDATE CASCADE,
Teacher_no smallint NOT NULL,
CONSTRAINT FK_MARK_TEACHER FOREIGN KEY(Teacher_no) REFERENCES TEACHER ON UPDATE CASCADE
)

CREATE TABLE TEACHER_DISCIPLINE
(
Discipline_no smallint NOT NULL,
CONSTRAINT FK_TEACHER_DISCIPLINE_DISCIPLINE FOREIGN KEY(Discipline_no) REFERENCES DISCIPLINE ON UPDATE CASCADE,
Teacher_no smallint NOT NULL,
CONSTRAINT FK_TEACHER_DISCIPLINE_TEACHER FOREIGN KEY(Teacher_no) REFERENCES TEACHER ON UPDATE CASCADE
)